---
title: "参考文献"
format: html
editor: visual
---

#### 参考文献（不分先后）：

Epskamp S, Borsboom D, Fried EI. Estimating psychological networks and their accuracy: A tutorial paper. Behav Res Methods. 2018 Feb;50(1):195-212. doi: 10.3758/s13428-017-0862-1. 

NETWORK PSYCHOMETRICSWITH R A Guide for Behavioral and Social Scientists

Zhu Z, Sun Y, Kuang Y, Yuan X, Gu H, Zhu J, Xing W. Contemporaneous symptom networks of multidimensional symptom experiences in cancer survivors: A network analysis. Cancer Med. 2023 Jan;12(1):663-673. doi: 10.1002/cam4.4904

Bellaert N, Morreale K, Tseng WL. Peer functioning difficulties may exacerbate symptoms of attention-deficit/hyperactivity disorder and irritability over time: a temporal network analysis. J Child Psychol Psychiatry. 2024 Jun;65(6):809-821. doi: 10.1111/jcpp.13911

Contreras A, Valiente C, Heeren A, Bentall R. A Temporal Network Approach to Paranoia: A Pilot Study. Front Psychol. 2020 Sep 18;11:544565. doi: 10.3389/fpsyg.2020.544565

Tao Y, Tang Q, Wang S, Zou X, Ma Z, Zhang L, Liu G, Liu X. The impact of long-term online learning on social anxiety and problematic smartphone use symptoms among secondary school students with different levels of fear of missing out: Evidence from a symptom network and longitudinal panel network analysis. J Behav Addict. 2024 Jan 9;13(1):102-119.

Haslbeck JMB, Borsboom D, Waldorp LJ. Moderated Network Models. Multivariate Behav Res. 2021 Mar-Apr;56(2):256-287. doi: 10.1080/00273171.2019.1677207

Haslbeck JMB, Bringmann LF, Waldorp LJ. A Tutorial on Estimating Time-Varying Vector Autoregressive Models. Multivariate Behav Res. 2021 Jan-Feb;56(1):120-149. doi: 10.1080/00273171.2020.1743630

Borsboom D, Cramer AO. Network analysis: an integrative approach to the structure of psychopathology. Annu Rev Clin Psychol. 2013;9:91-121. doi: 10.1146/annurev-clinpsy-050212-185608

Epskamp S, Waldorp LJ, Mõttus R, Borsboom D. The Gaussian Graphical Model in Cross-Sectional and Time-Series Data. Multivariate Behav Res. 2018 Jul-Aug;53(4):453-480. doi: 10.1080/00273171.2018.1454823

胡雁. 症状科学的发展及研究趋势\[J\]. 护士进修杂志,2023,38(24):2209-2213. DOI:10.16821/j.cnki.hsjx.2023.24.001.

朱政,胡天天,金依霖,等. 症状网络的基本概念及其在症状管理中的应用\[J\]. 护士进修杂志,2023,38(24):2214-2218,2224. DOI:10.16821/j.cnki.hsjx.2023.24.002.

杨中方,金依霖,何加敏,等. 基于数据类型的症状网络分类:同期网络动态网络和个体化网络\[J\]. 护士进修杂志,2023,38(24):2219-2224. DOI:10.16821/j.cnki.hsjx.2023.24.003.

朱政,胡天天,金依霖,等. 症状多层网络的类型和应用\[J\]. 护士进修杂志,2023,38(24):2225-2228. DOI:10.16821/j.cnki.hsjx.2023.24.004.

余骏雯,朱政,胡天天,等. 症状网络的特异性指标\[J\]. 护士进修杂志,2023,38(24):2229-2234,2245. DOI:10.16821/j.cnki.hsjx.2023.24.005.

朱政,余骏雯,杨中方,等. 症状同期网络的分析方法介绍及R软件实现\[J\]. 护士进修杂志,2023,38(24):2235-2239. DOI:10.16821/j.cnki.hsjx.2023.24.006.

余骏雯,胡天天,杨中方,等. 症状动态网络的分析方法介绍及R软件实现\[J\]. 护士进修杂志,2023,38(24):2240-2245. DOI:10.16821/j.cnki.hsjx.2023.24.007.

胡天天,余骏雯,何加敏,等. 个体化症状网络的应用方法及实现\[J\]. 护士进修杂志,2023,38(24):2246-2249. DOI:10.16821/j.cnki.hsjx.2023.24.008.

余骏雯,杨中方,何加敏,等. 症状网络研究的报告规范\[J\]. 护士进修杂志,2023,38(24):2250-2254,2261. DOI:10.16821/j.cnki.hsjx.2023.24.009.

蔡玉清,董书阳,袁帅,等. 变量间的网络分析模型及其应用\[J\]. 心理科学进展,2020,28(1):178-190. DOI:10.3724/SP.J.1042.2020.00178.

Robinaugh DJ, Hoekstra RHA, Toner ER, Borsboom D. The network approach to psychopathology: a review of the literature 2008-2018 and an agenda for future research. Psychol Med. 2020 Feb;50(3):353-366. doi: 10.1017/S0033291719003404

Hevey D. Network analysis: a brief overview and tutorial. Health Psychol Behav Med. 2018 Sep 25;6(1):301-328. doi: 10.1080/21642850.2018.1521283

Freichel R. Symptom Network Analysis Tools for Applied Researchers With Cross-Sectional and Panel Data - A Brief Overview and Multiverse Analysis. Psychol Rep. 2023 Nov 9:332941231213649. doi: 10.1177/00332941231213649.
